import type { Stage } from './types';

export const STAGES: Stage[] = [
  {
    id: 1,
    name: 'The Trigger',
    durationMs: 5000,
    description: 'Patient walks in. Front-desk staff types MyKad.',
  },
  {
    id: 2,
    name: 'The Verification Cascade',
    durationMs: 10000,
    description: 'EligibilityAgent checks 3 panels in parallel.',
  },
  {
    id: 3,
    name: 'The Consultation',
    durationMs: 4000,
    description: '45 minutes pass. The doctor sees the patient.',
  },
  {
    id: 4,
    name: 'The Submission Storm',
    durationMs: 10000,
    description: 'SubmissionAgent broadcasts canonical claim.',
  },
  {
    id: 5,
    name: 'The Time Skip',
    durationMs: 6000,
    description: 'Days and weeks pass. StatusAgent watches.',
  },
  {
    id: 6,
    name: 'The Reconciliation',
    durationMs: 18000,
    description: 'Remittance arrives. 5 agents reconcile.',
  },
  {
    id: 7,
    name: 'The Resolution',
    durationMs: 8000,
    description: "Dr. Vani's dashboard at end of month.",
  },
  {
    id: 8,
    name: 'The MMA Reveal',
    durationMs: 6000,
    description: 'Zoom out: 1,000 clinics.',
  },
  {
    id: 9,
    name: 'The CTA',
    durationMs: 5000,
    description: 'Pilot Monday. Live demo ends.',
  },
];

export const TOTAL_DURATION_MS = STAGES.reduce((sum, s) => sum + s.durationMs, 0);

export const STAGE_CONTENT = {
  stage1: {
    bubbleText: 'Patient just walked in. Let me verify his coverage.',
    patientName: 'Encik Faizal Rahman · 34 male',
    icNumber: '920101-10-1234',
  },
  stage2: {
    bubbleText:
      'I need to check MiCare, MediExpress, and PMCare. Old way: 3 phone calls, 17 minutes.',
    agentLabel: 'EligibilityAgent · calling 3 panels in parallel',
    tpas: [
      {
        name: 'MiCare',
        method: 'hotline' as const,
        response: 'Active · Berjaya Sompo OPD · RM 1,200 remaining · RM 0 copay',
        latency: 4700,
        status: 'success' as const,
        resolveAt: 5500,
      },
      {
        name: 'MediExpress',
        method: 'portal' as const,
        response: 'Active · Etiqa Corporate · RM 800 remaining · RM 5 copay',
        latency: 5400,
        status: 'success' as const,
        resolveAt: 6200,
      },
      {
        name: 'PMCare',
        method: 'app' as const,
        response: 'Employee resigned 14-Feb-2026',
        latency: 6000,
        status: 'failure' as const,
        resolveAt: 7000,
      },
    ],
    summary: '2 of 3 panels active · patient eligible at clinic',
    comparison: {
      old: '17 minutes',
      new: '6.8 seconds',
      kicker: "Patient hasn't even sat down.",
    },
  },
  stage3: {
    intro: '45 minutes pass.',
    soapLines: [
      'Patient: Encik Faizal Rahman',
      'DX: Acute pharyngitis (J02.9)',
      'Rx: Paracetamol 500mg, Amoxicillin 500mg',
      'MC: 2 days',
      'Consultation: RM 35.00',
    ],
    outro: 'The doctor finishes consultation.',
  },
  stage4: {
    bubbleText:
      'Old way: re-key into MiCare AND MediExpress portals. Two systems. Twelve minutes.',
    agentLabel: 'SubmissionAgent · broadcasting canonical claim to 2 eligible panels',
    claimLabel: 'ENCOUNTER DATA',
    claimLines: [
      'Patient: Encik Faizal Rahman (920101-10-1234)',
      'DX: J02.9 · Acute pharyngitis',
      'Rx: Paracetamol 500mg × 10, Amoxicillin 500mg × 15',
      'Consultation: RM 35.00',
      'Total: RM 35.00',
    ],
    targets: [
      {
        name: 'MiCare',
        method: 'api' as const,
        response: 'Acknowledged · Ref MC-2026-001847 · Status: in_review',
        latency: 2400,
        status: 'success' as const,
        resolveAt: 6000,
      },
      {
        name: 'MediExpress',
        method: 'api' as const,
        response: 'Acknowledged · Ref ME-26-003291 · Status: pending',
        latency: 3100,
        status: 'success' as const,
        resolveAt: 6800,
      },
    ],
    summary: '2 of 2 acknowledged · audit trail recorded',
    comparison:
      'Old way: 12 minutes, 2 portals, copy-paste errors. New way: 3.1 seconds, one click.',
  },
  stage5: {
    fromDate: '2026-02-14',
    toDate: '2026-04-17',
    sweepDurationMs: 6000,
    events: [
      { atProgress: 0.10, label: "Day 14 · MiCare moves claim to 'in review'" },
      { atProgress: 0.22, label: 'Day 27 · MediExpress requests additional documentation' },
      { atProgress: 0.30, label: 'Day 30 · FollowUpAgent sends payment reminder to MiCare', type: 'followup' as const },
      { atProgress: 0.38, label: 'Day 35 · StatusAgent auto-uploads supporting documents to MediExpress' },
      { atProgress: 0.48, label: 'Day 42 · FollowUpAgent escalates MediExpress — overdue 12 days', type: 'followup' as const },
      { atProgress: 0.58, label: "Day 47 · MediExpress moves to 'approved partial'" },
      { atProgress: 0.68, label: 'Day 52 · FollowUpAgent receives response from MiCare: "batch cycle April 18"', type: 'followup' as const },
      { atProgress: 0.80, label: "Day 58 · MiCare → 'paid' · remittance generated" },
      { atProgress: 0.92, label: "Day 62 · FollowUpAgent sends final notice to IHP — 85 days overdue", type: 'followup' as const },
    ],
    closingLine: "Dr. Vani didn't check a single portal, make a single call, or send a single email during these 62 days.",
  },
  stage6: {
    prePipeline: {
      bubbleText: 'Day 62. The remittance arrives.',
      remittanceHeader: 'MICARE SDN BHD · REMITTANCE MC-REM-2026-03-00184',
      remittanceLines: [
        'L01 · Lim S.K. · 14-Feb · RM 65 → RM 35 · admin adjustment',
        'L02 · Tan M.L. · 15-Feb · RM 45 → RM 45 · paid in full',
        'L03 · Faizal R. · 16-Feb · RM 80 → RM 72 · formulary cap',
        '...',
      ],
      pipelineLabel: 'ReconciliationAgent pipeline · 5 agents · sequential execution',
    },
    agents: [
      {
        name: 'IngestionAgent',
        model: 'Claude Haiku 4.5',
        icon: 'FileSearch' as const,
        startMs: 3000,
        workingText: 'Extracting line items from PDF via OCR...',
        snippetMs: 3500,
        snippet: 'Line 14 · Lim S.K. · 14-Feb-2026 · RM 65 billed · RM 35 paid',
        doneMs: 4300,
        resultText: '✓ Extracted 27 line items in 1.3s',
      },
      {
        name: 'MatchingAgent',
        model: 'Claude Sonnet 4.6',
        icon: 'GitMerge' as const,
        startMs: 4500,
        workingText: 'Fuzzy-matching 27 payment lines to 200 open claims...',
        snippetMs: 5500,
        snippet: null,
        doneMs: 6800,
        resultText: '✓ 25/27 matched · 2 flagged for review',
      },
      {
        name: 'VarianceAgent',
        model: 'Claude Sonnet 4.6',
        icon: 'AlertTriangle' as const,
        startMs: 7500,
        workingText: 'Classifying 8 variances...',
        snippetMs: null,
        snippet: null,
        doneMs: 11000,
        resultText: '✓ 8 variances · 6 UNEXPLAINED',
      },
      {
        name: 'AppealAgent',
        model: 'Claude Sonnet 4.6',
        icon: 'FileEdit' as const,
        startMs: 11500,
        workingText: 'Drafting 6 bilingual appeal letters (BM + EN)...',
        snippetMs: 12500,
        snippet: 'Re: Remittance MC-REM-2026-03-00184... We respectfully request written justification...',
        doneMs: 13200,
        resultText: '✓ 6 letters drafted · ready for review',
      },
      {
        name: 'AnalyticsAgent',
        model: 'Claude Haiku 4.5',
        icon: 'LineChart' as const,
        startMs: 13500,
        workingText: 'Rolling up dashboard metrics...',
        snippetMs: null,
        snippet: null,
        doneMs: 14700,
        resultText: '✓ Dashboard updated',
      },
    ],
    reasoningTrace: [
      "Examining Line 14: MiCare deducted RM 30 from RM 65 billed.",
      " Citing 'admin adjustment' as reason.",
      " Cross-referencing panel agreement... no matching clause.",
      " → CLASSIFICATION: UNEXPLAINED",
    ],
    reasoningStartMs: 8500,
    results: [
      {
        label: 'MATCHED CORRECTLY',
        value: 'RM 932',
        valueColor: 'positive' as const,
        sublabel: '20 lines · paid as billed',
        icon: 'CheckCircle' as const,
        pulse: false,
      },
      {
        label: 'EXPLAINED VARIANCES',
        value: 'RM 380',
        valueColor: 'amber' as const,
        sublabel: '5 lines · formulary caps & admin fees',
        icon: 'Info' as const,
        pulse: false,
      },
      {
        label: 'UNEXPLAINED',
        value: 'RM 6,210',
        valueColor: 'danger' as const,
        sublabel: '6 lines · 3 TPAs · letters drafted',
        icon: 'AlertCircle' as const,
        pulse: true,
      },
    ],
    closingLine: "Appeal letters in BM + EN ready for Dr. Vani's one-tap approval.",
  },
} as const;
