import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { X, Copy, Check } from 'lucide-react';
import { runAgent } from '../../lib/orchestrator';
import { appealAgent } from '../../lib/agents/appealAgent';
import type { AppealOutput } from '../../lib/agents/appealAgent';
import type { Clinic } from '../../data/types';
import type { EXCEPTIONS_DEMO } from '../../data/seed';

type AppealDrawerProps = {
  exception: typeof EXCEPTIONS_DEMO[number];
  clinic: Clinic;
  onClose: () => void;
};

export function AppealDrawer({ exception, clinic, onClose }: AppealDrawerProps) {
  const [tab, setTab] = useState<'en' | 'bm'>('en');
  const [result, setResult] = useState<AppealOutput | null>(null);
  const [loading, setLoading] = useState(true);
  const [latencyMs, setLatencyMs] = useState<number | null>(null);
  const [usedFallback, setUsedFallback] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setResult(null);

    runAgent(appealAgent, {
      tpaName: exception.tpa,
      patientName: exception.patient,
      patientIcHashed: exception.patientIc,
      serviceDate: exception.date,
      billedRm: exception.billed,
      paidRm: exception.paid,
      deductionReason: exception.reason,
      remittanceRef: exception.remittanceRef,
      doctorName: clinic.doctor,
      doctorMmc: clinic.mmc,
      clinicName: clinic.name,
    }, { liveCall: true }).then(({ output, invocation }) => {
      if (cancelled) return;
      setResult(output);
      setLatencyMs(invocation.latencyMs ?? null);
      setUsedFallback(invocation.usedFallback);
      setLoading(false);
    });

    return () => { cancelled = true; };
  }, [exception.id]);

  const letterText = result ? (tab === 'en' ? result.englishLetter : result.bahasaLetter) : '';

  function handleCopy() {
    navigator.clipboard.writeText(letterText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <motion.div
      className="fixed inset-0 z-50 flex justify-end"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <div className="absolute inset-0 bg-background/60" onClick={onClose} />
      <motion.div
        className="relative w-full max-w-lg bg-surface-solid border-l border-border h-full overflow-y-auto"
        initial={{ x: '100%' }}
        animate={{ x: 0 }}
        exit={{ x: '100%' }}
        transition={{ type: 'spring', stiffness: 300, damping: 30 }}
      >
        <div className="sticky top-0 bg-surface-solid border-b border-border p-4 flex items-center justify-between z-10">
          <div>
            <h3 className="font-display text-lg text-ink">Appeal Letter</h3>
            <p className="text-xs text-muted font-mono">{exception.tpa} · {exception.patient}</p>
          </div>
          <button onClick={onClose} className="p-1 text-muted hover:text-ink" type="button" aria-label="Close">
            <X size={20} />
          </button>
        </div>

        <div className="p-4">
          {!usedFallback && latencyMs !== null && (
            <p className="text-xs font-mono text-primary mb-3">
              Generated by DeepSeek Chat · {latencyMs}ms
            </p>
          )}

          {/* Tabs */}
          <div className="flex gap-1 mb-4">
            <button
              onClick={() => setTab('en')}
              className={`px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
                tab === 'en' ? 'bg-primary-soft text-primary' : 'text-muted hover:text-body'
              }`}
              type="button"
            >
              English
            </button>
            <button
              onClick={() => setTab('bm')}
              className={`px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
                tab === 'bm' ? 'bg-primary-soft text-primary' : 'text-muted hover:text-body'
              }`}
              type="button"
            >
              Bahasa Malaysia
            </button>
          </div>

          {loading ? (
            <div className="space-y-3">
              <p className="text-sm text-body">Drafting bilingual appeal letter with DeepSeek...</p>
              {Array.from({ length: 8 }).map((_, i) => (
                <div
                  key={i}
                  className="h-3 rounded bg-surface-elevated animate-pulse"
                  style={{ width: `${60 + Math.random() * 40}%` }}
                />
              ))}
            </div>
          ) : (
            <div className="relative">
              <button
                onClick={handleCopy}
                className="absolute top-0 right-0 flex items-center gap-1 text-xs text-muted hover:text-primary transition-colors"
                type="button"
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? 'Copied' : 'Copy'}
              </button>
              <pre className="font-mono text-sm text-body whitespace-pre-wrap leading-relaxed pr-16">
                {letterText}
              </pre>
            </div>
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}
